# Generated by Django 4.1.1 on 2022-09-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='genero',
            field=models.CharField(default='sin genero', help_text='Genero', max_length=50),
        ),
        migrations.AlterField(
            model_name='actores',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
