# Generated by Django 4.1.1 on 2022-09-26 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_peliculas_genero_alter_actores_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='actores',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='peliculas.actores'),
        ),
    ]
