# Generated by Django 4.1.1 on 2022-09-26 04:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_peliculas_actores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peliculas',
            name='genero',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='descripcion',
            field=models.TextField(default='', help_text='Resumen del libro'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='actores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peliculas.actores'),
        ),
        migrations.CreateModel(
            name='InstanciaPeliculas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Id unico para esta pelicula', primary_key=True, serialize=False)),
                ('fechaEstreno', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('t', 'Terror'), ('c', 'Comedia'), ('p', 'Parodia'), ('a', 'Accion'), ('s', 'Suspenso'), ('d', 'Drama'), ('cf', 'Ciencia-Ficcion'), ('cr', 'Comedia-Romantica')], default='t', help_text='Ingresa el genero', max_length=2)),
                ('pelicula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peliculas.peliculas')),
            ],
        ),
    ]
