# Generated by Django 4.1.1 on 2022-09-26 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_remove_peliculas_genero_peliculas_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actores',
            new_name='Directores',
        ),
        migrations.RenameField(
            model_name='peliculas',
            old_name='actores',
            new_name='directores',
        ),
    ]
