# Generated by Django 4.1.1 on 2022-10-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0005_rename_actores_directores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directores',
            name='bio',
            field=models.TextField(default='', max_length=500),
        ),
    ]
